// pwa/src/lib/components/panel/right/MetadataPanel.svelte
<script lang="ts">
	import type { LibraryImage } from '$lib/types/library';

	export let selectedImage: LibraryImage | null = null;
	export let metadata: Record<string, unknown> | null = null;
	export let isLoading = false;
	export let errorMessage = '';

	const keyOrder = ['FNumber', 'ExposureTime', 'PhotographicSensitivity', 'ISO', 'FocalLengthIn35mmFilm', 'LensModel'];
	const labelMap: Record<string, string> = {
		FNumber: 'Aperture',
		ExposureTime: 'Shutter Speed',
		PhotographicSensitivity: 'ISO',
		ISO: 'ISO',
		FocalLengthIn35mmFilm: 'Focal Length',
		LensModel: 'Lens'
	};

	function formatTag(tag: string) {
		return tag.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2');
	}

	function formatValue(value: unknown) {
		if (value === null || value === undefined) return '—';
		if (typeof value === 'number') return Number.isFinite(value) ? value.toString() : '—';
		if (typeof value === 'object') return JSON.stringify(value);
		return String(value);
	}
</script>

<div class="flex h-full flex-col">
	<div class="border-b border-border-color/60 pb-3">
		<p class="text-xs uppercase tracking-[0.2em] text-text-secondary">Metadata</p>
		<h3 class="text-base font-semibold text-text-primary">Capture Details</h3>
	</div>

	<div class="flex-1 overflow-y-auto pt-3 text-sm text-text-secondary">
		{#if !selectedImage}
			<p class="text-center">No image selected.</p>
		{:else if isLoading}
			<p class="text-center">Loading metadata…</p>
		{:else if errorMessage}
			<p class="text-center text-red-300">{errorMessage}</p>
		{:else}
			<div class="flex flex-col gap-4">
				<div class="rounded-lg border border-border-color/60 bg-bg-primary/40 p-3">
					<p class="text-xs font-semibold text-text-primary">File Properties</p>
					<div class="mt-2 grid gap-1 text-xs">
						<div class="flex items-center justify-between">
							<span>Filename</span>
							<span class="text-text-primary">{selectedImage.name}</span>
						</div>
						<div class="flex items-center justify-between">
							<span>Size</span>
							<span class="text-text-primary">{Math.round(selectedImage.size / 1024)} KB</span>
						</div>
						<div class="flex items-center justify-between">
							<span>Modified</span>
							<span class="text-text-primary">
								{new Date(selectedImage.lastModified).toLocaleString()}
							</span>
						</div>
					</div>
				</div>

				{#if metadata}
					<div class="rounded-lg border border-border-color/60 bg-bg-primary/40 p-3">
						<p class="text-xs font-semibold text-text-primary">Key Camera Settings</p>
						<div class="mt-2 grid gap-1 text-xs">
							{#each keyOrder as key}
								{#if metadata[key] !== undefined}
									<div class="flex items-center justify-between">
										<span>{labelMap[key] ?? key}</span>
										<span class="text-text-primary">{formatValue(metadata[key])}</span>
									</div>
								{/if}
							{/each}
						</div>
					</div>

					<div class="rounded-lg border border-border-color/60 bg-bg-primary/40 p-3">
						<p class="text-xs font-semibold text-text-primary">All EXIF Entries</p>
						<div class="mt-2 max-h-64 overflow-y-auto text-xs">
							{#each Object.entries(metadata).sort((a, b) => a[0].localeCompare(b[0])) as [key, value]}
								<div class="grid grid-cols-[1fr,1fr] gap-2 border-b border-border-color/30 py-1 last:border-none">
									<span class="truncate">{formatTag(key)}</span>
									<span class="truncate text-text-primary" title={formatValue(value)}>
										{formatValue(value)}
									</span>
								</div>
							{/each}
						</div>
					</div>
				{:else}
					<p class="text-center text-xs text-text-secondary">No EXIF data found.</p>
				{/if}
			</div>
		{/if}
	</div>
</div>

// src/components/panel/right/MetadataPanel.tsx
import React, { useMemo } from 'react';
import { SelectedImage } from '../../ui/AppProperties';

interface CameraSetting {
  format?(value: number): void;
  label: string;
}

interface CameraSettings {
  [index: string]: CameraSetting;
  ExposureTime: CameraSetting;
  FNumber: CameraSetting;
  FocalLengthIn35mmFilm: CameraSetting;
  LensModel: CameraSetting;
  PhotographicSensitivity: CameraSetting;
}

interface GPSData {
  altitude: number | null;
  lat: number | null;
  lon: number | null;
}

interface MetaDataItemProps {
  label: string;
  value: any;
}

interface MetaDataPanelProps {
  selectedImage: SelectedImage;
}

function formatExifTag(str: string) {
  if (!str) {
    return '';
  }
  return str.replace(/([a-z])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2');
}

function parseDms(dmsString: string) {
  if (!dmsString) {
    return null;
  }
  const parts = dmsString.match(/(\d+\.?\d*)\s+deg\s+(\d+\.?\d*)\s+min\s+(\d+\.?\d*)\s+sec/);
  if (!parts) {
    return null;
  }
  const degrees = parseFloat(parts[1]);
  const minutes = parseFloat(parts[2]);
  const seconds = parseFloat(parts[3]);
  return degrees + minutes / 60 + seconds / 3600;
}

function MetadataItem({ label, value }: MetaDataItemProps) {
  return (
    <div className="grid grid-cols-3 gap-2 text-xs py-1.5 px-2 rounded odd:bg-bg-primary">
      <p className="font-semibold text-text-primary col-span-1 break-words">{label}</p>
      <p className="text-text-secondary col-span-2 break-words truncate" title={String(value)}>
        {String(value)}
      </p>
    </div>
  );
}

const KEY_CAMERA_SETTINGS_MAP: CameraSettings = {
  FNumber: {
    format: (value: number) => `${value}`,
    label: 'Aperture',
  },
  ExposureTime: {
    format: (value: number) => `${value}`,
    label: 'Shutter Speed',
  },
  PhotographicSensitivity: {
    label: 'ISO',
  },
  FocalLengthIn35mmFilm: {
    format: (value: number) => (String(value).endsWith('mm') ? value : `${value} mm`),
    label: 'Focal Length',
  },
  LensModel: {
    format: (value: number) => String(value).replace(/"/g, ''),
    label: 'Lens',
  },
};

const KEY_SETTINGS_ORDER: Array<string> = [
  'FNumber',
  'ExposureTime',
  'PhotographicSensitivity',
  'FocalLengthIn35mmFilm',
  'LensModel',
];

export default function MetadataPanel({ selectedImage }: MetaDataPanelProps) {
  const { keyCameraSettings, gpsData, otherExifEntries } = useMemo(() => {
    const exif = selectedImage?.exif || {};

    const keyCameraSettings = KEY_SETTINGS_ORDER.map((key) => {
      const value = exif[key];
      if (value === undefined || value === null) {
        return null;
      }
      const config = KEY_CAMERA_SETTINGS_MAP[key];
      const formattedValue = config.format ? config.format(value) : value;
      return {
        key: key,
        label: config.label,
        value: formattedValue,
      };
    }).filter(Boolean);

    const latStr = exif.GPSLatitude;
    const latRef = exif.GPSLatitudeRef;
    const lonStr = exif.GPSLongitude;
    const lonRef = exif.GPSLongitudeRef;

    let gpsData: GPSData = { lat: null, lon: null, altitude: exif.GPSAltitude || null };
    if (latStr && latRef && lonStr && lonRef) {
      const parsedLat = parseDms(latStr);
      const parsedLon = parseDms(lonStr);
      if (parsedLat !== null && parsedLon !== null) {
        gpsData.lat = latRef.toUpperCase() === 'S' ? -parsedLat : parsedLat;
        gpsData.lon = lonRef.toUpperCase() === 'W' ? -parsedLon : parsedLon;
      }
    }

    const otherExifEntries = Object.entries(exif).sort(([keyA], [keyB]) => keyA.localeCompare(keyB));

    return { keyCameraSettings, gpsData, otherExifEntries };
  }, [selectedImage?.exif]);

  const hasGps = gpsData.lat !== null && gpsData.lon !== null;

  return (
    <div className="flex flex-col h-full">
      <div className="p-4 flex justify-between items-center flex-shrink-0 border-b border-surface">
        <h2 className="text-xl font-bold text-primary text-shadow-shiny">Metadata</h2>
      </div>
      <div className="flex-grow overflow-y-auto p-4 text-text-secondary">
        {selectedImage ? (
          <div className="flex flex-col gap-6">
            <div>
              <h3 className="text-base font-bold text-text-primary mb-2 border-b border-surface pb-1">
                File Properties
              </h3>
              <div className="flex flex-col gap-1">
                <MetadataItem label="Filename" value={selectedImage.path.split(/[\\/]/).pop()} />
                <MetadataItem label="Dimensions" value={`${selectedImage.width} x ${selectedImage.height}`} />
                {selectedImage.exif?.DateTimeOriginal && (
                  <MetadataItem label="Capture Date" value={selectedImage.exif.DateTimeOriginal} />
                )}
              </div>
            </div>

            {keyCameraSettings.length > 0 && (
              <div>
                <h3 className="text-base font-bold text-text-primary mb-2 border-b border-surface pb-1">
                  Key Camera Settings
                </h3>
                <div className="flex flex-col gap-1">
                  {keyCameraSettings.map((item: any) => (
                    <MetadataItem key={item.key} label={item.label} value={item.value} />
                  ))}
                </div>
              </div>
            )}

            {hasGps && gpsData?.lat && gpsData?.lon && (
              <div>
                <h3 className="text-base font-bold text-text-primary mb-2 border-b border-surface pb-1">
                  GPS Location
                </h3>
                <div className="flex flex-col gap-2">
                  <div className="relative rounded-md overflow-hidden border border-surface">
                    <iframe
                      className="pointer-events-none"
                      frameBorder="0"
                      height="180"
                      loading="lazy"
                      marginHeight={0}
                      marginWidth={0}
                      scrolling="no"
                      src={`https://www.openstreetmap.org/export/embed.html?bbox=${gpsData.lon - 0.01}%2C${
                        gpsData.lat - 0.01
                      }%2C${gpsData.lon + 0.01}%2C${gpsData.lat + 0.01}&layer=mapnik&marker=${gpsData.lat}%2C${
                        gpsData.lon
                      }`}
                      width="100%"
                    ></iframe>
                    <a
                      className="absolute inset-0 cursor-pointer"
                      href={`https://www.openstreetmap.org/?mlat=${gpsData.lat}&mlon=${gpsData.lon}#map=15/${gpsData.lat}/${gpsData.lon}`}
                      rel="noopener noreferrer"
                      target="_blank"
                      title="Click to open map in a new tab"
                    ></a>
                  </div>
                  <div className="flex flex-col gap-1">
                    <MetadataItem label="Latitude" value={gpsData.lat?.toFixed(6)} />
                    <MetadataItem label="Longitude" value={gpsData.lon?.toFixed(6)} />
                    {gpsData.altitude && <MetadataItem label="Altitude" value={gpsData.altitude} />}
                  </div>
                </div>
              </div>
            )}

            {otherExifEntries.length > 0 && (
              <div>
                <h3 className="text-base font-bold text-text-primary mb-2 border-b border-surface pb-1">
                  All EXIF Data
                </h3>
                <div className="flex flex-col gap-1">
                  {otherExifEntries.map(([tag, value]) => (
                    <MetadataItem key={tag} label={formatExifTag(tag)} value={value} />
                  ))}
                </div>
              </div>
            )}

            {Object.keys(selectedImage.exif || {}).length === 0 && (
              <p className="text-xs text-center text-text-secondary mt-4">No EXIF data found in this file.</p>
            )}
          </div>
        ) : (
          <p className="text-center">No image selected.</p>
        )}
      </div>
    </div>
  );
}
