// src/components/panel/BottomBar.tsx
import { useState, useEffect, useRef } from 'react';
import { Star, Copy, ClipboardPaste, RotateCcw, ChevronUp, ChevronDown, Check, Save, Loader2, Settings } from 'lucide-react';
import clsx from 'clsx';
import Filmstrip from './Filmstrip';
import { GLOBAL_KEYS, ImageFile, SelectedImage, ThumbnailAspectRatio } from '../ui/AppProperties';

interface BottomBarProps {
  filmstripHeight?: number;
  imageList?: Array<ImageFile>;
  imageRatings?: Record<string, number> | null;
  isCopied: boolean;
  isCopyDisabled: boolean;
  isExportDisabled?: boolean;
  isFilmstripVisible?: boolean;
  isLibraryView?: boolean;
  isLoading?: boolean;
  isPasted: boolean;
  isPasteDisabled: boolean;
  isRatingDisabled?: boolean;
  isResetDisabled?: boolean;
  isResizing?: boolean;
  multiSelectedPaths?: Array<string>;
  onClearSelection?(): void;
  onContextMenu?(event: any, path: string): void;
  onCopy(): void;
  onExportClick?(): void;
  onImageSelect?(path: string, event: any): void;
  onOpenCopyPasteSettings?(): void;
  onPaste(): void;
  onRate(rate: number): void;
  onReset?(): void;
  onZoomChange?(zoomValue: number, fitToWindow?: boolean): void;
  rating: number;
  selectedImage?: SelectedImage;
  setIsFilmstripVisible?(isVisible: boolean): void;
  thumbnails?: Record<string, string>;
  thumbnailAspectRatio: ThumbnailAspectRatio;
  zoom?: number;
  displaySize?: { width: number; height: number };
  originalSize?: { width: number; height: number };
  baseRenderSize?: { width: number; height: number };
}

interface StarRatingProps {
  disabled: boolean;
  onRate(rate: number): void;
  rating: number;
}

const StarRating = ({ rating, onRate, disabled }: StarRatingProps) => {
  return (
    <div className={clsx('flex items-center gap-1', disabled && 'cursor-not-allowed')}>
      {[...Array(5)].map((_, index: number) => {
        const starValue = index + 1;
        return (
          <button
            className="disabled:cursor-not-allowed"
            disabled={disabled}
            key={starValue}
            onClick={() => !disabled && onRate(starValue === rating ? 0 : starValue)}
            title={disabled ? 'Select an image to rate' : `Rate ${starValue} star${starValue > 1 ? 's' : ''}`}
          >
            <Star
              size={18}
              className={clsx(
                'transition-colors duration-150',
                disabled
                  ? 'text-text-secondary opacity-40'
                  : starValue <= rating
                  ? 'fill-accent text-accent'
                  : 'text-text-secondary hover:text-accent',
              )}
            />
          </button>
        );
      })}
    </div>
  );
};

export default function BottomBar({
  filmstripHeight,
  imageList = [],
  imageRatings,
  isCopied,
  isCopyDisabled,
  isExportDisabled,
  isFilmstripVisible,
  isLibraryView = false,
  isLoading = false,
  isPasted,
  isPasteDisabled,
  isRatingDisabled = false,
  isResetDisabled = false,
  isResizing,
  multiSelectedPaths = [],
  onClearSelection,
  onContextMenu,
  onCopy,
  onExportClick,
  onImageSelect,
  onOpenCopyPasteSettings,
  onPaste,
  onRate,
  onReset,
  onZoomChange = () => {},
  rating,
  selectedImage,
  setIsFilmstripVisible,
  thumbnails,
  thumbnailAspectRatio,
  zoom = 0,
  displaySize,
  originalSize,
  baseRenderSize,
}: BottomBarProps) {
  const [isEditingPercent, setIsEditingPercent] = useState(false);
  const [percentInputValue, setPercentInputValue] = useState('');
  const isDraggingSlider = useRef(false);
  const percentInputRef = useRef<HTMLInputElement>(null);
  const [isZoomLabelHovered, setIsZoomLabelHovered] = useState(false);

  const isZoomReady = !isLoading && originalSize && originalSize.width > 0 && displaySize && displaySize.width > 0;
  const currentOriginalPercent = isZoomReady ? displaySize.width / originalSize.width : 1.0;

  const [latchedSliderValue, setLatchedSliderValue] = useState(1.0);
  const [latchedDisplayPercent, setLatchedDisplayPercent] = useState(100);

  useEffect(() => {
    if (isZoomReady && !isDraggingSlider.current) {
      setLatchedSliderValue(currentOriginalPercent);
      setLatchedDisplayPercent(Math.round(currentOriginalPercent * 100));
    }
  }, [currentOriginalPercent, isZoomReady]);

  const handleSliderChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newZoom = parseFloat(e.target.value);
    setLatchedSliderValue(newZoom);
    if (originalSize && baseRenderSize) {
      const calculatedPercent = (newZoom / (originalSize.width / baseRenderSize.width)) * 100;
      setLatchedDisplayPercent(Math.round(calculatedPercent));
    }
    onZoomChange(newZoom);
  };

  const handleMouseDown = () => {
    isDraggingSlider.current = true;
  };

  const handleMouseUp = () => {
    isDraggingSlider.current = false;
    if (isZoomReady) {
      setLatchedDisplayPercent(Math.round(currentOriginalPercent * 100));
    }
  };

  const handleZoomKeyDown = (e: React.KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && ['z', 'y'].includes(e.key.toLowerCase())) {
      (e.target as HTMLElement).blur();
      return;
    }
    if (GLOBAL_KEYS.includes(e.key)) {
      (e.target as HTMLElement).blur();
    }
  };

  const handleResetZoom = () => {
    onZoomChange(0, true);
  };

  const handlePercentClick = () => {
    if (!isZoomReady) return;
    setIsEditingPercent(true);
    setPercentInputValue(latchedDisplayPercent.toString());
    setTimeout(() => {
      percentInputRef.current?.focus();
      percentInputRef.current?.select();
    }, 0);
  };

  const handlePercentSubmit = () => {
    const value = parseFloat(percentInputValue);
    if (!isNaN(value)) {
      const originalPercent = value / 100;
      const clampedPercent = Math.max(0.1, Math.min(2.0, originalPercent));
      onZoomChange(clampedPercent);
    }
    setIsEditingPercent(false);
    setPercentInputValue('');
  };

  const handlePercentKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') handlePercentSubmit();
    else if (e.key === 'Escape') {
      setIsEditingPercent(false);
      setPercentInputValue('');
    }
    e.stopPropagation();
  };

  return (
    <div className="flex-shrink-0 bg-bg-secondary rounded-lg flex flex-col">
      {!isLibraryView && (
        <div
          className={clsx(
            'overflow-hidden',
            !isResizing && 'transition-all duration-300 ease-in-out',
            isFilmstripVisible ? 'p-2' : 'p-0',
          )}
          style={{ height: isFilmstripVisible ? `${filmstripHeight}px` : '0px' }}
        >
          <Filmstrip
            imageList={imageList}
            imageRatings={imageRatings}
            isLoading={isLoading}
            multiSelectedPaths={multiSelectedPaths}
            onClearSelection={onClearSelection}
            onContextMenu={onContextMenu}
            onImageSelect={onImageSelect}
            selectedImage={selectedImage}
            thumbnails={thumbnails}
            thumbnailAspectRatio={thumbnailAspectRatio}
          />
        </div>
      )}

      <div
        className={clsx(
          'flex-shrink-0 h-10 flex items-center justify-between px-3',
          !isLibraryView && isFilmstripVisible && 'border-t border-surface',
        )}
      >
        <div className="flex items-center gap-4">
          <StarRating rating={rating} onRate={onRate} disabled={isRatingDisabled} />
          <div className="h-5 w-px bg-surface"></div>
          <div className="flex items-center gap-2">
            <button
              className="w-8 h-8 flex items-center justify-center rounded-md text-text-secondary hover:bg-surface hover:text-text-primary transition-colors disabled:opacity-40 disabled:hover:bg-transparent disabled:cursor-not-allowed"
              disabled={isCopyDisabled}
              onClick={onCopy}
              title="Copy Settings"
            >
              {isCopied ? <Check size={18} className="text-green-500 animate-pop-in" /> : <Copy size={18} />}
            </button>
            <button
              className="w-8 h-8 flex items-center justify-center rounded-md text-text-secondary hover:bg-surface hover:text-text-primary transition-colors disabled:opacity-40 disabled:hover:bg-transparent disabled:cursor-not-allowed"
              disabled={isPasteDisabled}
              onClick={onPaste}
              title="Paste Settings"
            >
              {isPasted ? <Check size={18} className="text-green-500 animate-pop-in" /> : <ClipboardPaste size={18} />}
            </button>
            <button
              className="w-8 h-8 flex items-center justify-center rounded-md text-text-secondary hover:bg-surface hover:text-text-primary transition-colors"
              onClick={onOpenCopyPasteSettings}
              title="Copy / Paste Settings"
            >
              <Settings size={18} />
            </button>
          </div>
        </div>

        {isLibraryView ? (
          <div className="flex items-center gap-2">
            <button
              className="w-8 h-8 flex items-center justify-center rounded-md text-text-secondary hover:bg-surface hover:text-text-primary transition-colors disabled:opacity-40 disabled:hover:bg-transparent disabled:cursor-not-allowed"
              disabled={isResetDisabled}
              onClick={onReset}
              title="Reset All Adjustments"
            >
              <RotateCcw size={18} />
            </button>
            <button
              className="w-8 h-8 flex items-center justify-center rounded-md text-text-secondary hover:bg-surface hover:text-text-primary transition-colors disabled:opacity-40 disabled:hover:bg-transparent disabled:cursor-not-allowed"
              disabled={isExportDisabled}
              onClick={onExportClick}
              title="Export Selected Images"
            >
              <Save size={18} />
            </button>
          </div>
        ) : (
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 w-56">
              <div
                className="relative w-12 h-full flex items-center justify-end cursor-pointer"
                onClick={handleResetZoom}
                onMouseEnter={() => setIsZoomLabelHovered(true)}
                onMouseLeave={() => setIsZoomLabelHovered(false)}
                title="Reset Zoom to Fit Window"
              >
                <span className="absolute right-0 text-xs text-text-secondary select-none text-right w-max transition-colors hover:text-text-primary">
                  {isZoomLabelHovered ? 'Reset Zoom' : 'Zoom'}
                </span>
              </div>
              <input
                type="range"
                min={0.1}
                max={2.0}
                step="0.05"
                value={latchedSliderValue}
                onChange={handleSliderChange}
                onKeyDown={handleZoomKeyDown}
                onMouseDown={handleMouseDown}
                onMouseUp={handleMouseUp}
                onTouchStart={handleMouseDown}
                onTouchEnd={handleMouseUp}
                onDoubleClick={handleResetZoom}
                className="flex-1 h-1 bg-surface rounded-lg appearance-none cursor-pointer accent-accent"
              />
              <div className="relative text-xs text-text-secondary w-6 text-right flex items-center justify-end h-5 gap-1">
                {isEditingPercent ? (
                  <input
                    ref={percentInputRef}
                    type="text"
                    value={percentInputValue}
                    onChange={(e) => setPercentInputValue(e.target.value)}
                    onKeyDown={handlePercentKeyDown}
                    onBlur={handlePercentSubmit}
                    className="w-full text-xs text-text-primary bg-bg-primary border border-border-color rounded px-1 text-right"
                    style={{ fontSize: '12px', height: '18px' }}
                  />
                ) : (
                  <span
                    onClick={handlePercentClick}
                    className="cursor-pointer hover:text-text-primary transition-colors select-none"
                    title="Click to enter custom zoom percentage"
                  >
                    {latchedDisplayPercent}%
                  </span>
                )}
                {isLoading && !isEditingPercent && <Loader2 size={12} className="animate-spin ml-1" />}
              </div>
            </div>
            <button
              className="p-1.5 rounded-md text-text-secondary hover:bg-surface hover:text-text-primary transition-colors"
              onClick={() => setIsFilmstripVisible?.(!isFilmstripVisible)}
              title={isFilmstripVisible ? 'Collapse Filmstrip' : 'Expand Filmstrip'}
            >
              {isFilmstripVisible ? <ChevronDown size={18} /> : <ChevronUp size={18} />}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// pwa/src/lib/components/panel/BottomBar.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import Filmstrip from './Filmstrip.svelte';
	import type { LibraryImage } from '$lib/types/library';

	export let images: LibraryImage[] = [];
	export let selectedId: string | null = null;
	export let rating = 0;
	export let zoom = 1;
	export let isLibraryView = false;
	export let isLoading = false;
	export let filmstripVisible = true;
	export let filmstripHeight = 120;
	export let isCopied = false;
	export let isPasted = false;
	export let isCopyDisabled = false;
	export let isPasteDisabled = false;
	export let isExportDisabled = false;
	export let isResetDisabled = false;

	const dispatch = createEventDispatcher<{
		select: { image: LibraryImage };
		rate: { rating: number };
		zoom: { value: number; fit: boolean };
		toggleFilmstrip: {};
		copy: {};
		paste: {};
		settings: {};
		reset: {};
		export: {};
	}>();

	const ratingSteps = [1, 2, 3, 4, 5];

	$: displayZoom = zoom > 0 ? Math.round(zoom * 100) : 100;

	function handleRate(value: number) {
		dispatch('rate', { rating: value === rating ? 0 : value });
	}

	function handleZoomInput(event: Event) {
		const value = Number((event.target as HTMLInputElement).value);
		if (Number.isFinite(value)) {
			dispatch('zoom', { value, fit: false });
		}
	}

	function handleResetZoom() {
		dispatch('zoom', { value: 0, fit: true });
	}
</script>

<div class="flex-shrink-0 rounded-lg bg-bg-secondary">
	{#if !isLibraryView}
		<div
			class={`overflow-hidden ${filmstripVisible ? 'transition-all duration-300 ease-in-out' : ''}`}
			style={`height: ${filmstripVisible ? filmstripHeight : 0}px;`}
		>
			<div class="w-full p-2" style={`height: ${filmstripHeight}px;`}>
				<Filmstrip
					{images}
					{selectedId}
					height={filmstripHeight - 16}
					on:select={(event) => dispatch('select', event.detail)}
				/>
			</div>
		</div>
	{/if}

	<div
		class={`flex h-10 items-center justify-between px-3 ${
			!isLibraryView ? 'border-t border-transparent' : ''
		}`}
	>
		<div class="flex items-center gap-4">
			<div class="flex items-center gap-1">
				{#each ratingSteps as value}
					<button
						class={`rounded px-1 text-xs ${
							value <= rating
								? 'bg-accent text-button-text'
								: 'text-text-secondary hover:text-text-primary'
						}`}
						disabled={isLibraryView ? false : false}
						on:click={() => handleRate(value)}
						title={`Rate ${value}`}
					>
						{value}
					</button>
				{/each}
			</div>
			<div class="h-5 w-px bg-surface"></div>
			<div class="flex items-center gap-2">
				<button
					class="rounded-md px-2 py-1 text-xs text-text-secondary hover:bg-surface hover:text-text-primary disabled:opacity-40"
					disabled={isCopyDisabled}
					on:click={() => dispatch('copy', {})}
				>
					{isCopied ? 'Copied' : 'Copy'}
				</button>
				<button
					class="rounded-md px-2 py-1 text-xs text-text-secondary hover:bg-surface hover:text-text-primary disabled:opacity-40"
					disabled={isPasteDisabled}
					on:click={() => dispatch('paste', {})}
				>
					{isPasted ? 'Pasted' : 'Paste'}
				</button>
				<button
					class="rounded-md px-2 py-1 text-xs text-text-secondary hover:bg-surface hover:text-text-primary"
					on:click={() => dispatch('settings', {})}
				>
					Settings
				</button>
			</div>
		</div>
		<div class="flex-grow" />
		{#if isLibraryView}
			<div class="flex items-center gap-2">
				<button
					class="rounded-md px-2 py-1 text-xs text-text-secondary hover:bg-surface hover:text-text-primary disabled:opacity-40"
					disabled={isResetDisabled}
					on:click={() => dispatch('reset', {})}
				>
					Reset
				</button>
				<button
					class="rounded-md bg-accent px-2 py-1 text-xs text-button-text disabled:opacity-40"
					disabled={isExportDisabled}
					on:click={() => dispatch('export', {})}
				>
					Export
				</button>
			</div>
		{:else}
			<div class="flex items-center gap-4">
				<div class="flex items-center gap-2">
					<button
						class="rounded-md px-2 py-1 text-xs text-text-secondary hover:text-text-primary"
						on:click={handleResetZoom}
					>
						Zoom
					</button>
					<div class="relative h-5 w-32">
						<div class="absolute top-1/2 h-1.5 w-full -translate-y-1/2 rounded-full bg-surface" />
						<input
							class="slider-input absolute top-1/2 h-1.5 w-full -translate-y-1/2 appearance-none bg-transparent"
							type="range"
							min={0.1}
							max={2.0}
							step={0.05}
							value={zoom === 0 ? 1 : zoom}
							on:input={handleZoomInput}
						/>
					</div>
					<span class="w-10 text-right text-xs text-text-secondary">{displayZoom}%</span>
				</div>
				<div class="h-5 w-px bg-surface"></div>
				<button
					class="rounded-md px-2 py-1 text-xs text-text-secondary hover:bg-surface hover:text-text-primary"
					on:click={() => dispatch('toggleFilmstrip', {})}
				>
					{filmstripVisible ? 'Hide' : 'Show'} Filmstrip
				</button>
			</div>
		{/if}
	</div>
</div>
